### ISSUE TITLE
请问这个语法错误是我环境问题还是代码问题？

### ISSUE THREAD

**Issue by JK-Sun** [jasl-lab/form_core#1]
/form_core/lib/form_core.rb:7:in `require': 
/form_core/lib/form_core/coders/hash_coder.rb:8: syntax error, unexpected '.' (SyntaxError)
      obj&.serializable_hash || {}
           ^

**Comment by jasl** [comment]
你 Ruby 版本？

**Comment by jasl** [comment]
我看了下那段代码，这里用了单身狗运算符 `&.`，所以需要至少 Ruby 2.3，况且 2.2 已经结束支持，建议升级，2.2 升级到 2.3 不会有兼容问题

**Comment by yiichou** [comment]
单身狗运算符 ..........
