### ISSUE TITLE
Nested form field类型的字段无法删除，外键约束错误

### ISSUE THREAD

**Issue by txbleehom** [jasl-lab/form_core#11]
![image](https://user-images.githubusercontent.com/6263354/99611016-d8053380-2a4d-11eb-8fe9-12845ee43c92.png)
错误如图，

![image](https://user-images.githubusercontent.com/6263354/99611331-74c7d100-2a4e-11eb-92ea-da8654754c4b.png)

**Comment by jasl** [comment]
可否展示一下你的表单定义的截图？

**Comment by txbleehom** [comment]
@jasl 上面截图就是demo程序未做任何修改，因为在自己项目里引用了test/dummy示例，发现删除不了，然后运行demo程序发现也删除不了

**Comment by jasl** [comment]
我的意思是表单定义那个页面的截图 这样我根据你的在我这边定义一套相同的 看看能否复现

**Comment by txbleehom** [comment]
@jasl 在demo程序里我新建的定义如下图，就新建了一个Nested form field字段，然后在fields里加了两个字段，其他未做任何上设置
![image](https://user-images.githubusercontent.com/6263354/99636992-2ed73100-2a7f-11eb-942b-b75550b119fe.png)
![image](https://user-images.githubusercontent.com/6263354/99636894-0cddae80-2a7f-11eb-9c2d-a054543f24c5.png)
![image](https://user-images.githubusercontent.com/6263354/99636949-1cf58e00-2a7f-11eb-8688-bb6d4797d42d.png)
![image](https://user-images.githubusercontent.com/6263354/99637134-62b25680-2a7f-11eb-9dee-b3a7a5ec5172.png)

**Comment by jasl** [comment]
最后一个问题哈，你有没有改过字段类型？

**Comment by txbleehom** [comment]
@jasl 没有，最新代码什么都没改，demo跑起来后直接新建表然后新建一个Nested form field字段，然后删除这个字段就上面的错

**Comment by jasl** [comment]
好的，感谢，我晚上到家来尝试复现一下

**Comment by jasl** [comment]
修复了，你试试，可能是一个低级错误，删除嵌套表单字段的时候，没有正确级联删除这个字段关联的嵌套表单

**Comment by txbleehom** [comment]
现在可以了，谢谢
