### ISSUE TITLE
ArgumentError (unknown keyword: :owner):

### ISSUE THREAD

**Issue by promisepreston** [jasl-lab/form_core#12]
Hi, thank you so much for this gem.
I just found it and it seems to fit into what I really want. I am currently running the demo app, but I run into this error when I try to create a form:

    ArgumentError (unknown keyword: :owner):

![Screenshot from 2021-01-08 22-20-12](https://user-images.githubusercontent.com/19772307/104065261-ba5b7b80-51ff-11eb-8d09-90d1f0b74384.png)

How do you think I can get this fixed.

**Comment by jasl** [comment]
What's your Ruby version?

**Comment by promisepreston** [comment]
My Ruby version is 2.7.2 while rails is 6.1.0

**Comment by jasl** [comment]
I also use Ruby 2.7.2
Just upgrade the dummy app using 6.1.0 can't reproduce the problem.
if you're testing the dummy app, you need to delete `dummy/db/development.sqlite` and do `rails db:migrate` because Rails 6.1 change ActiveStorage model


But I think it's relates to my another gem (form core depends on it),
please do `bundle update` and try again

**Comment by promisepreston** [comment]
So this is the way I set up the app before encountering the issue.

After I cloned the app I changed the Rails version in the Gemfile to ~> 6.1.0 , and the Ruby version in .rubyversiom file to 2.7.2. I the deleted the Gemfile.lock before running bundle install, which installed all the gems afresh without. I think the Rails version also got updated to 6.1.1.

Don’t know if this is why I ran into that issue, maybe a gem dependency of fore_core is causing the issue.

What do you advise?

**Comment by jasl** [comment]
> So this is the way I set up the app before encountering the issue.
> 
> After I cloned the app I changed the Rails version in the Gemfile to ~> 6.1.0 , and the Ruby version in .rubyversiom file to 2.7.2. I the deleted the Gemfile.lock before running bundle install, which installed all the gems afresh without. I think the Rails version also got updated to 6.1.1.
> 
> Don’t know if this is why I ran into that issue, maybe a gem dependency of fore_core is causing the issue.
> 
> What do you advise?

I upgrade to Rails 6.1 on form_core master, could you `git pull` then `bundle` or just do a clean clone?

**Comment by promisepreston** [comment]
Ok, let me try that now.
Thank you.

**Comment by promisepreston** [comment]
It works very fine.
Thank you so much.
I will close this issue now.
Thank you so much for your assistance.

Do you have documentation on how this fore_core gem can be integrated into a Rails project?
Something that I can follow, or will I have to look at how you implemented it for the dummy app?

**Comment by jasl** [comment]
> It works very fine.
> Thank you so much.
> I will close this issue now.
> Thank you so much for your assistance.

Sorry, I didn't write the document, this was a prototype for my consultant work, I feel it may usful so I open sourced here.
AFAIK, this gem has some business users, but I don't feel satisfied about the form and field abstraction, still finding how to do it better.

For now, I suggest just copy codes (my another gem script_core also copied some fields for demo show), I have no plan do breaking change on it.
